language: objective-c
osx_image: xcode9.1

xcode_project: Marvin.xcodeproj

env: 
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

#xcode_scheme:
#    - Marvin
#    - MarvinUI
    
script: 
    - xcodebuild -project Marvin.xcodeproj -scheme MarvinUI -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.1' test
    - xcodebuild clean build -project Marvin.xcodeproj -scheme Marvin -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.1' test
      #if [ $TRAVIS_XCODE_SCHEME == "MarvinUI" ]; then 
       
      #fi

notifications:
    slack: monk:RpAnzCI98kpQLAkIGXEMGZSH
    email:
        recipients:
        - arsuffi@webmonks.it
        - cardaci@webmonks.it
        - lancellotti@webmonks.it
        on_success: never # default: change
        on_failure: always # default: always
