language: objective-c
osx_image: xcode9.1

xcode_project: Marvin.xcodeproj

env: 
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

xcode_scheme:
    - Marvin
    - MarvinUI
    
script: 
    - |
      if [ $xcode_scheme == "MarvinUI" ]; then 
        xcodebuild clean && xcodebuild -project Marvin.xcodeproj -scheme MarvinUI && xcodebuild -project Marvin.xcodeproj -scheme MarvinUI -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.1'; 
      fi
    - |
      if [ $xcode_scheme == "Marvin" ]; then 
        xcodebuild clean && xcodebuild -project Marvin.xcodeproj -scheme Marvin && xcodebuild -project Marvin.xcodeproj -scheme Marvin -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.1'; 
      fi
