language: objective-c
osx_image: xcode9.1

xcode_project: Marvin.xcodeproj

xcode_scheme:
  - Marvin
  - MarvinUI

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

script: 
  - xcodebuild clean
  - xcodebuild -project xcode_project -scheme Marvin
  - xcodebuild -project xcode_project -scheme MarvinUI
  - xcodebuild -project xcode_project -scheme Marvin -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.1'
  - xcodebuild -project xcode_project -scheme MarvinUI -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.1'
